version: "3.8"
services:
  node-server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    env_file:
      - ./config/db.env

    volumes:
      - data:/data/db

volumes:
  data:
