version: "3.8"
services:
  db:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "gameet"

    volumes:
      - data:/data/db

volumes:
  data:
